name: Pages

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: |
            mkdir dist
            cp -R src/* dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secret.GITHUB_TOKEN}}
          publish_dir: ./dist
        
      